name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install software
      run: sudo apt install gcc-8-multilib g++-8-multilib gcc-multilib g++-multilib
    - name: make
      run: make -C src -j3 debug

