name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: apt install g++-32bit
    - name: configure2
      run: apt-cache search gcc
    - name: make
      run: make -C src -j3 debug
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
