name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update list of available software
      run: sudo apt-get update
    - name: install software
      run: sudo apt-get install gcc-multilib g++-multilib
    - name: make
      run: cd src && scons
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
